import type { CarPickerResult } from "@/components/CarPicker";
import type { PartInspection } from "@/types/inspection";
import { isIdbUrl, getIdbKey, resolveMediaUrls, collectIdbKeys, deleteBlobs } from "@/lib/media/mediaStore";

export interface DiagnosticFile {
  name: string;
  type: string;
  dataUrl: string;
}

export interface ReportDraft {
  id: string;
  currentStep: number;
  totalSteps: number;
  vin: string;
  vinUnreadable?: boolean;
  plate: string;
  mileage: string;
  mileageMatchesClaimed: boolean;
  carResult: CarPickerResult | null;
  legalSkipped: boolean;
  legalLoaded: boolean;
  inspections: Record<string, PartInspection>;
  inspectionPhotos: string[];
  diagnosticFiles: DiagnosticFile[];
  diagnosticNote: string;
  docsOwnerMatch: boolean | null;
  docsVinMatch: boolean | null;
  docsEngineMatch: boolean | null;
  underhoodChecks: Record<string, boolean>;
  underhoodNote: string;
  underhoodPhotos: string[];
  bodyPaintFrom: number;
  bodyPaintTo: number;
  structPaintFrom: number;
  structPaintTo: number;
  bodyStructural: Record<string, { left: number; right: number }>;
  bodyDamageElements: Record<string, boolean>;
  bodyStructuralInspections: Record<string, PartInspection>;
  bodyUndercarriageInspections: Record<string, PartInspection>;
  bodyGeometryOk: boolean;
  bodyNote: string;
  bodyPhotos: string[];
  glassInspections: Record<string, PartInspection>;
  glassPhotos: string[];
  glassNote: string;
  interiorNoDamage: boolean;
  interiorTags: string[];
  functionsAllOk: boolean;
  functionsTags: string[];
  interiorPhotos: string[];
  interiorNote: string;
  wheelsTiresOk: boolean;
  wheelsTiresTags: string[];
  wheelsRimsOk: boolean;
  wheelsRimsTags: string[];
  wheelsBrakesOk: boolean;
  wheelsBrakesTags: string[];
  wheelsPhotos: string[];
  wheelsNote: string;
  wheelsSuspensionOk: boolean;
  wheelsSuspensionTags: string[];
  tdConducted: boolean | null;
  tdEngineOk: boolean;
  tdEngineTags: string[];
  tdGearboxOk: boolean;
  tdGearboxTags: string[];
  tdSteeringOk: boolean;
  tdSteeringTags: string[];
  tdRideOk: boolean;
  tdRideTags: string[];
  tdBrakeRideOk: boolean;
  tdBrakeRideTags: string[];
  tdPhotos: string[];
  tdNote: string;
  mediaFiles: { id: string; url: string; type: "image" | "video" }[];
  engineVolume: string;
  engineType: string;
  gearboxType: string;
  driveType: string;
  color: string;
  trim: string;
  ownersCount: string;
  inspectionCity: string;
  inspectionDate: string;
  adLink: string;
  summaryNote: string;
  summaryNoteEdited?: boolean;
  summaryNoteAutoGenerated?: string;
  expertConclusion?: string;
  updatedAt: string;
}

const STORAGE_KEY = "report_drafts";
const COMPRESSION_CACHE_LIMIT = 200;
const SMALL_JPEG_DATA_URL_LENGTH = 200_000;
const COMPRESS_BATCH_SIZE = 4;
const YIELD_EVERY = 8;
const compressionCache = new Map<string, string>();

function getCachedCompression(dataUrl: string): string | null {
  const cached = compressionCache.get(dataUrl);
  if (!cached) return null;
  compressionCache.delete(dataUrl);
  compressionCache.set(dataUrl, cached);
  return cached;
}

function setCachedCompression(source: string, compressed: string): string {
  if (compressionCache.has(source)) compressionCache.delete(source);
  compressionCache.set(source, compressed);
  if (compressionCache.size > COMPRESSION_CACHE_LIMIT) {
    const oldestKey = compressionCache.keys().next().value;
    if (oldestKey) compressionCache.delete(oldestKey);
  }
  return compressed;
}

function yieldToBrowser(): Promise<void> {
  return new Promise((resolve) => {
    if (typeof window !== "undefined" && "requestAnimationFrame" in window) {
      window.requestAnimationFrame(() => resolve());
      return;
    }
    setTimeout(resolve, 0);
  });
}

/**
 * compressImage — сжимает base64-изображение до указанной ширины и качества JPEG.
 * Используется для уменьшения объёма данных перед сохранением в localStorage.
 * Не-изображения возвращаются без изменений.
 */
function compressImage(dataUrl: string, maxWidth = 800, quality = 0.6): Promise<string> {
  return new Promise((resolve) => {
    // IDB keys are tiny strings — no compression needed
    if (isIdbUrl(dataUrl)) {
      resolve(dataUrl);
      return;
    }
    const cached = getCachedCompression(dataUrl);
    if (cached) {
      resolve(cached);
      return;
    }
    if (!dataUrl.startsWith("data:image")) {
      resolve(dataUrl);
      return;
    }
    if (dataUrl.startsWith("data:image/jpeg") && dataUrl.length <= SMALL_JPEG_DATA_URL_LENGTH) {
      resolve(setCachedCompression(dataUrl, dataUrl));
      return;
    }
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      let w = img.width;
      let h = img.height;
      if (w > maxWidth) {
        h = (h * maxWidth) / w;
        w = maxWidth;
      }
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext("2d");
      ctx?.drawImage(img, 0, 0, w, h);
      resolve(setCachedCompression(dataUrl, canvas.toDataURL("image/jpeg", quality)));
    };
    img.onerror = () => resolve(setCachedCompression(dataUrl, dataUrl));
    img.src = dataUrl;
  });
}

async function compressUrlList(urls: string[]): Promise<string[]> {
  const result = [...urls];
  for (let start = 0; start < urls.length; start += COMPRESS_BATCH_SIZE) {
    const batch = urls.slice(start, start + COMPRESS_BATCH_SIZE);
    const compressedBatch = await Promise.all(batch.map((url) => compressImage(url)));
    compressedBatch.forEach((compressed, index) => {
      result[start + index] = compressed;
    });
    if (start + COMPRESS_BATCH_SIZE < urls.length && (start + COMPRESS_BATCH_SIZE) % YIELD_EVERY === 0) {
      await yieldToBrowser();
    }
  }
  return result;
}

async function compressInspectionRecord(
  inspections: Record<string, PartInspection>,
): Promise<Record<string, PartInspection>> {
  const output: Record<string, PartInspection> = {};
  let processed = 0;

  for (const [key, inspection] of Object.entries(inspections)) {
    if (!inspection) continue;

    const nextInspection: PartInspection = {
      ...inspection,
      photos: await compressUrlList(inspection.photos ?? []),
    };

    if (inspection.tagPhotos) {
      const tagPhotosEntries = await Promise.all(
        Object.entries(inspection.tagPhotos).map(async ([tag, urls]) => [tag, await compressUrlList(urls)] as const),
      );
      nextInspection.tagPhotos = Object.fromEntries(tagPhotosEntries);
    }

    output[key] = nextInspection;
    processed += 1;
    if (processed % YIELD_EVERY === 0) {
      await yieldToBrowser();
    }
  }

  return output;
}

/**
 * compressDraftPhotos — рекурсивно сжимает все фотографии внутри черновика:
 * массивы фото каждого раздела и вложенные фото в инспекциях (photos, tagPhotos).
 * Возвращает новый объект черновика с уменьшенными изображениями.
 */
async function compressDraftPhotos(draft: ReportDraft): Promise<ReportDraft> {
  const result = { ...draft };
  result.inspectionPhotos = await compressUrlList(result.inspectionPhotos);
  result.underhoodPhotos = await compressUrlList(result.underhoodPhotos);
  result.bodyPhotos = await compressUrlList(result.bodyPhotos);
  result.glassPhotos = await compressUrlList(result.glassPhotos);
  result.interiorPhotos = await compressUrlList(result.interiorPhotos);
  result.wheelsPhotos = await compressUrlList(result.wheelsPhotos);
  result.tdPhotos = await compressUrlList(result.tdPhotos);

  result.inspections = await compressInspectionRecord(result.inspections);
  result.bodyStructuralInspections = await compressInspectionRecord(result.bodyStructuralInspections);
  result.bodyUndercarriageInspections = await compressInspectionRecord(result.bodyUndercarriageInspections);
  result.glassInspections = await compressInspectionRecord(result.glassInspections);

  return result;
}

/**
 * loadDrafts — загружает массив черновиков отчётов из localStorage.
 * При ошибке парсинга возвращает пустой массив.
 */
export function loadDrafts(): ReportDraft[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

/**
 * saveDraft — сжимает фото и сохраняет черновик в localStorage.
 * Если найден существующий черновик с тем же VIN (но другим id) — обновляет его.
 * При переполнении хранилища пытается удалить старые черновики и повторить.
 */
export async function saveDraft(draft: ReportDraft): Promise<void> {
  const compressed = await compressDraftPhotos(draft);
  const drafts = loadDrafts();
  const existingByVin = compressed.vin
    ? drafts.find((d) => d.id !== compressed.id && d.vin === compressed.vin)
    : null;

  const updated = existingByVin
    ? drafts.map((d) =>
        d.id === existingByVin.id
          ? { ...compressed, id: existingByVin.id, updatedAt: new Date().toISOString().slice(0, 10) }
          : d
      )
    : (() => {
        const filtered = drafts.filter((d) => d.id !== compressed.id);
        filtered.unshift({ ...compressed, updatedAt: new Date().toISOString().slice(0, 10) });
        return filtered;
      })();

  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  } catch (e) {
    console.warn("Draft save failed (storage full), trying to free space...", e);
    // Remove oldest drafts to free space — single attempt, no recursion
    const trimmed = updated.slice(0, Math.max(1, updated.length - 1));
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(trimmed));
    } catch {
      console.error("Cannot save draft — localStorage is full.");
      throw e; // Propagate so useDebouncedAutosave can activate cooldown
    }
  }
}

/**
 * deleteDraft — удаляет черновик по id из localStorage.
 */
export function deleteDraft(id: string): void {
  const drafts = loadDrafts().filter((d) => d.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(drafts));
}

/**
 * getDraftDisplayInfo — возвращает отображаемое название и год для карточки черновика.
 * Приоритет: бренд+модель → VIN → госномер → «Новый отчёт».
 */
export function getDraftDisplayInfo(draft: ReportDraft) {
  const brand = draft.carResult?.brand.name ?? "";
  const model = draft.carResult?.model.model ?? "";
  const label = brand && model ? `${brand} ${model}` : draft.vin || draft.plate || "Новый отчёт";
  const year = draft.carResult?.generation?.generation ?? null;
  return { label, year };
}
